micronaut:
  application:
    name: sherlock
  server:
    context-path: /sherlock
    port: 5555
    cors:
      enabled: true
  security:
    authentication: bearer
    endpoints:
      login:
        path: /api/login
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: m2hm9T3VdnQK9hGpbarULdDQ5DCZcq3O
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:m2hm9T3VdnQK9hGpbarULdDQ5DCZcq30}"'
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
      - pattern: /rapidoc/**
        access:
          - isAnonymous()
      - pattern: /redoc/**
        access:
          - isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  openapi:
    server:
      context-path: /sherlock
netty:
  default:
    allocator:
      max-order: 3
jena: http://localhost:3030/iremus
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jackson:
  always-serialize-errors-as-list: false